version: "3"
# networks:
#   default:
#     driver: bridge
networks:
  default:
    external:
      name: fininza-net
services:
  nats:
    image: nats
    # networks:
    #   - fininza-net
    #   - default
    command: 
      - "-p"
      - "4222"
      - "-cluster"
      - "nats://0.0.0.0:6222"
    # expose:
    #   - "6222"
    ports:
      - "8222:8222"
      - "4222:4222"
      - "6222:6222"
  nats-1:
    image: nats
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    depends_on:
      - nats
  nats-2:
    image: nats
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    depends_on:
      - nats
